config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  root controller: :landing, action: :index

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comment
  validates :title, presence: true
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
  def create
    @articles = Article.new article_params

    if @articles.save
      redirect_to landing_index_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_articles

  def new
    @comment = Comment.new(article: @article)
  end

  def create
    @email = (params[:comment][:email] =~ /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
    if @email == nil
      flash[:alert] = "WRONG EMAIL FORMAT!"
      redirect_to article_path(@article)
    else
    @comment = Comment.new(article: @article, email: params[:comment][:email], comment: params[:comment][:comment])
    if @comment.save
      redirect_to article_path(@article)
    end
    end
  end

  private

  def get_articles
  @article = Article.find(params[:article_id])
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<h2>Publish your own article</h2>
<%= form_for Article.new do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p>Published 2016-05-24</p>

<%= link_to 'Add comment', new_article_comment_path(@article) %>
<% unless @article.comment.empty? %>
  <h4><%= @article.title %>´s comments</h4>

  <ul>
    <% @article.comment.each do |comment| %>
      <li><%= comment.comment %></li>
      <li><%= comment.email %></li>
    <% end %>
  </ul>
<% end %>

app/views/comments/new.html.erb
<h2> New comment for <%= @article.title %></h2>

<%= form_for [@article, @comment] do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/landing/index.html.erb
<h1>Our Articles</h1>
<%= link_to "Publish article" , new_article_path %>
<ul>
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title , article_path(article) %><br />
    <%= article.content %>
    <p>Written by <%= article.author %> at <%= article.created_at.strftime("%Y-%m-%d") %></p>
    <p>Comments for this article</p>
    <% article.comment.each do |cont| %>
    <%= cont.comment %><br />
    <%= cont.email %><br />
    <% end %><br />
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:alert] %>
          <div id="alert">
             <%= flash[:alert] %>
          </div>
    <% end %>
    <%= yield %>
  </body>
</html>